server:
  port: 8080

spring:
  application:
    name: first-test-app
  datasource:
    url: jdbc:postgresql://localhost:5432/zipkin_test
    username: postgres
    password: mysecretpassword
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: topic
    ssl:
      enabled: false

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"