version: "3.8"

services:
#  elasticsearch:
#    image: elasticsearch:8.5.0
#    container_name: elasticsearch
#    restart: always
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65535
#        hard: 65535
#    environment:
#      - CLUSTER_NAME=docker-cluster
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
#      - xpack.security.enabled=false
#      - http.max_content_length=1024mb
#      - bootstrap.memory_lock=true

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
#    environment:
#      - "STORAGE_TYPE=elasticsearch"
#      - "ES_HOSTS=http://192.168.1.19:9200"
#    depends_on:
#      - elasticsearch
